### ISSUE TITLE
How to organize data before using src/data/datasets_merge.py

### ISSUE THREAD

**Issue by ashish-kubade** [AILab-UniFI/GNN-TableExtraction#4]
I have downloaded the two respective datasets, PubTab1m and Publaynet. However, while running the src/data/datasets_merge.py, I am getting error around file locations. Can anyone please share how to organize the downloaded dataset, so that the path are properly read from datasets_merge.py ?

TIA

**Comment by andreagemelli** [comment]
Hi @ashj9 ,
we have created another repo for the dataset that you find here [https://github.com/AILab-UniFI/cte-dataset](https://github.com/AILab-UniFI/cte-dataset). You should find all the answers there, and an update version of the scripts.
Let us know,
A.

**Comment by ashish-kubade** [comment]
HI @andreagemelli Thank you for this update. I tried using the code in cte-dataset repository and able to create the merged dataset.

But further, could you please mention about the using the merge dataset to create features?
There are src/data/tables_creation.py, src/data/tables_preprocess.py, src/data/graph_creation.py files but in which order these should be used? before using src/features/features_build.py?
